modLoader="javafml"
loaderVersion="[3,)"
license="GNU GPLv3"
issueTrackerURL="${github}/issues"
[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
displayURL="${github}"
logoFile="icon.png"
authors="${author}"
description="${description}"
[[dependencies.chunky]]
   modId="neoforge"
   mandatory=true
   versionRange="[21.0-beta,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.chunky]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.21,1.22)"
   ordering="NONE"
   side="BOTH"
